language: node_js

dist: trusty

node_js:
  - "6"

before_install:
  - npm install -g grunt-cli@1.2.0

install:
  - npm install

script: gulp build

cache:
  directories:
    - node_modules

deploy:
  provider: npm
  email: "henry19.chavez@gmail.com"
  api_key: $GITHUB_AUTH_TOKEN
